Loading input data from CSV

In [10]:
import numpy as np

with open("/content/Data_1.csv") as file_name:
    array = np.loadtxt(file_name, delimiter=",", dtype=np.float_,skiprows=1,max_rows=50,usecols=range(1,6))
with open("/content/Data_1.csv") as file_name:
    target = np.loadtxt(file_name, delimiter=",", dtype=np.float_,skiprows=1,max_rows=50,usecols=6)

array=np.matrix(array)
target=np.matrix(target)
print(array)
print(target)

[[1.   0.06 0.3  0.07 0.84]
 [1.   0.72 0.63 0.05 0.51]
 [1.   0.59 0.08 0.18 0.81]
 [1.   0.97 0.18 0.92 0.54]
 [1.   0.46 0.08 0.07 0.45]
 [1.   0.14 0.82 0.08 0.16]
 [1.   0.65 0.53 0.38 0.44]
 [1.   0.29 0.02 0.18 0.76]
 [1.   0.84 0.22 0.5  0.4 ]
 [1.   0.19 0.09 0.59 0.88]
 [1.   0.89 0.83 0.24 0.39]
 [1.   0.91 0.4  0.41 0.75]
 [1.   0.98 0.02 0.55 0.56]
 [1.   0.86 0.36 0.09 0.48]
 [1.   0.49 0.17 0.25 0.3 ]
 [1.   0.07 0.95 0.55 0.57]
 [1.   0.8  0.16 0.94 0.17]
 [1.   0.59 0.84 0.69 0.13]
 [1.   0.23 0.43 0.58 0.26]
 [1.   0.61 0.68 0.44 0.42]
 [1.   0.3  0.86 0.69 0.45]
 [1.   0.84 0.51 0.71 0.1 ]
 [1.   0.04 0.61 0.7  0.83]
 [1.   0.88 0.68 0.75 0.13]
 [1.   0.17 0.36 0.11 0.76]
 [1.   0.01 0.24 0.39 0.47]
 [1.   0.66 0.37 0.38 0.26]
 [1.   0.57 0.95 0.26 0.45]
 [1.   0.55 0.39 0.32 0.79]
 [1.   0.05 0.16 0.18 0.71]
 [1.   0.07 1.   0.7  0.12]
 [1.   0.51 0.73 0.19 0.99]
 [1.   0.23 0.6  0.23 0.14]
 [1.   0.62 0.   0.43 0.26]
 [1.   0.2  0.8  0.85 0.41]
 [1.   0.44 0.41 0.8

Dont run below part -- this is testing the array

In [8]:
list = []
for i in target:
  #print (i)
  list.append([i])
print(list)
target = np.array(list)

[[matrix([[0.51, 0.68, 0.52, 0.75, 0.45, 0.41, 0.43, 0.47, 0.66, 0.54,
         0.56, 0.84, 0.69, 0.5 , 0.27, 0.5 , 0.39, 0.69, 0.34, 0.61,
         0.7 , 0.53, 0.65, 0.78, 0.54, 0.24, 0.68, 0.79, 0.57, 0.14,
         0.8 , 0.51, 0.63, 0.45, 0.75, 0.76, 0.58, 0.59, 0.5 , 0.65,
         0.57, 0.65, 0.41, 0.39, 0.62, 0.73, 0.48, 0.79, 0.46, 0.77]])]]


Continue the execution

In [11]:
x=array
print(array.shape)
print(type(target))
print(target.shape)
target=target

(50, 5)
<class 'numpy.matrix'>
(1, 50)


Creating sigmoul 

In [12]:
def sigmoul (x, deriv=False):
  if(deriv==True):
    return(x*(1-x))
  return(1/(1+np.exp(-x)))

Back prapogration
#seed 

In [14]:
np.random.seed(2)


#synapses


In [15]:
syn0 = 2*np.random.random((5,50)) - 1
syn1 = 2*np.random.random((50,1)) - 1 

#Training

In [16]:
for j in range(2000):
  #layer
  l0 = array
  l1 = sigmoul(np.dot(l0,syn0))
  l2 = sigmoul(np.dot(l1,syn1))
  #backprogation
  l2_error = target - l2
  if (j % 100) == 0:
    print ('Error ' + str(np.mean(np.abs(l2_error))))
  #calculate delta
  l2_delta = l2_error*sigmoul(l2, deriv=True)
  l1_error = l2_delta.dot(syn1.T)
  l1_delta = l1_error * sigmoul(l1, deriv=True)
  #update weight
  syn1 += l1.T.dot(l2_delta)
  syn0 += l0.T.dot(l1_delta)

Error 0.15562388321520682


ValueError: ignored

#Print output after training


In [ ]:
print ( "later training output --- %s " %(l2))

later training output --- [[0.81480383]
 [0.66400507]
 [0.69945904]
 [0.45849346]
 [0.72137741]
 [0.75166329]
 [0.62029499]
 [0.75860922]
 [0.55366391]
 [0.71653022]
 [0.58063738]
 [0.57370022]
 [0.52383184]
 [0.62353868]
 [0.67399505]
 [0.71447785]
 [0.47478722]
 [0.5555495 ]
 [0.66709461]
 [0.61597648]
 [0.63798073]
 [0.49483712]
 [0.71405418]
 [0.48003094]
 [0.78731044]
 [0.75799326]
 [0.60651767]
 [0.65577478]
 [0.67949147]
 [0.79637898]
 [0.66081485]
 [0.71769475]
 [0.71429524]
 [0.61299241]
 [0.62650743]
 [0.6048606 ]
 [0.73318295]
 [0.65697278]
 [0.78517561]
 [0.70645821]
 [0.54907094]
 [0.45918204]
 [0.70749919]
 [0.66746513]
 [0.60049231]
 [0.68473286]
 [0.80146494]
 [0.63734446]
 [0.77388926]
 [0.61852624]] 
